### ISSUE TITLE
Resource Association Links

### ISSUE THREAD

**Issue by alexrobin** [opengeospatial/ogcapi-connected-systems#2]
Need to decide on the best approach to implement links between resources since there is no guidance in OGC API common on this subject.

For JSON encoded resources, the following options are possible:

- Put all associations in the links[] at the end of the resource.
- Insert links as direct properties of the resource object.
- A mix of both (perhaps treat many-to-one and one-to-many/many-to-many relations differently?).

There is also the question of the content of the link itself.
Our experience shows that a URL is often not enough, so we would like to provide extra info in a link:
- `title` to capture a human readable name for the target resource
- `uid` to capture unique ID of target resource in case the link is broken (for one-to-one relation)
- `mediaType`

**Comment by ghobona** [comment]
@alexrobin `title` and `type` are already provided by _OGC API - Common - Part 1: Core_. See the schema [here](https://beta.schemas.opengis.net/ogcapi/common/part1/0.1/core/openapi/schemas/link.yaml).

Note that OGC API - Common, OGC API - Features, OGC API - Tiles, OGC API - EDR and many of the candidate Standards reference [RFC 8288](https://tools.ietf.org/html/rfc8288).

Note that [RFC 8288](https://tools.ietf.org/html/rfc8288) establishes the link-params "rel", "anchor", and "rev" (which are part of the general link model), as well as "hreflang", "media", "title", "title*", and "type".

**Comment by cportele** [comment]
@alexrobin - In the work on JSON-FG we looked into this, too. See https://docs.ogc.org/DRAFTS/21-045.html#relationships_and_links.

**Comment by cportele** [comment]
@alexrobin - Not really. I personally tend to include the links in the resource properties, because intuitively this looks like the more natural representation and as typically easier to parse for clients (a get with a key vs iterating over a list). This may be different for more generic relationship types that are not specific to the feature type. An example for this could be the spatial topological relationships (the `ogc:contains` example).

**Comment by alexrobin** [comment]
@cportele Ok, thanks. I have been following a similar approach so far. In any case, we should make sure all OGC APIs share the same model for the link object.
