### ISSUE TITLE
Build instructions for standards documents out of date?

### ISSUE THREAD

**Issue by matthijskooijman** [opengeospatial/ogcapi-connected-systems#27]
In `api/part1/standard/README.adoc` and `api/part2/standard/README.adoc` it is documented that building works using `make`. However, that seems to fail due to missing files (`metanorma.source.files`, `metanorma.source.built_targets` and `metanorma.formats`). Instead, running `./build.sh` does seem to produce working HTML docs, so maybe the docs are out of date?

**Comment by matthijskooijman** [comment]
> Instead, running ./build.sh does seem to produce working HTML docs, so maybe the docs are out of date?

Hm, turns out that was not correct - turns out that there was already a .html file commited into the repo that I thought was locally created by `build.sh`. Running `./build.sh` actually produces a lot of errors/warnings, but does not generate a HTML file (it does generate `23-001r0.err.html`, `23-001r0.xml.abort` and `iev/` and `relation/`). None of the errors seem fatal (and also adding `--no-strict` does not help to generate HTML even with errors), except maybe Style: `Document must contain at least one clause` (but it seems that the main adoc file properly includes the various sections/clauses, asciidoctor can also generate HTML for them).

**Comment by alexrobin** [comment]
I am about to push my latest version this week that now builds with the latest version of Metanorma. I will let you know when available. You're correct that the `build.sh` script is the one to use.

**Comment by matthijskooijman** [comment]
Thanks!

**Comment by alexrobin** [comment]
You should now be able to build the document for part 1 of the standard.
Alternatively, the HTML version of the latest draft is available [here](https://opengeospatial.github.io/ogcapi-connected-systems/api/part1/standard/23-001r0.html).

**Comment by matthijskooijman** [comment]
Thanks! I can indeed build part1 as expected now. Part 2 still fails, but from your message that is to be expected still. So let's leave this issue open until that is fixed as well?

Also, the reason I wanted to build in the first place (a section level error that messed up section numbering) is also fixed by the latest changes, so no more need to build myself anyway :-)

**Comment by alexrobin** [comment]
Good, thanks. Yes I noticed that session numbering issue.
I'll leave this open until I fix part 2.

**Comment by alexrobin** [comment]
Everything is now building, but be aware that the document for part2 is not ready for review yet.
