### ISSUE TITLE
Definition of 'sampledFeature' and alignment with SSN terms

### ISSUE THREAD

**Issue by dr-shorthair** [opengeospatial/ogcapi-connected-systems#51]
I noticed an inconsistency on the definition of one of the Sampling Feature Associations in Table 17

| CS term | SSN term | text definition |
| --- | --- | --- |
| `sampledFeature` | `sosa:isSampleOf` | the ultimate feature of interest that is being sampled or controlled. |

In OMS and SSN, the relation `isSampleOf`​ links a Sample to the _proximate_​ feature of interest, not the ultimate FoI. There may then be a chain of further samples before you reach the ultimate FoI. The additional properties `hasOriginalSample`​ and `hasSampledFeature`​ provide shortcuts. See diagrams in the SSN-Ext paper, which inspired OMS and the SSN update - https://www.w3.org/TR/vocab-ssn-ext/#ultimate-feature-of-interest

**Comment by alexrobin** [comment]
Ok, I'll fix this in the table
