### ISSUE TITLE
sosa:Platform not (yet?) a subclass of sosa:System

### ISSUE THREAD

**Issue by dr-shorthair** [opengeospatial/ogcapi-connected-systems#52]
In section 9.1 I see the following note: 

> NOTE 2:    System resources are used to model all subclasses of [ssn:System](http://www.w3.org/ns/ssn/System), including [sosa:Sensor](http://www.w3.org/ns/sosa/Sensor), [sosa:Actuator](http://www.w3.org/ns/sosa/Actuator), [sosa:Sampler](http://www.w3.org/ns/sosa/Sampler), as well as [sosa:Platform](http://www.w3.org/ns/sosa/Platform). Semantic tagging is used to provide the exact type.

`sosa:Platform` is not a subclass of `sosa:System`. The sentence is ambiguous but this incorrect interpretation is available.

**Comment by alexrobin** [comment]
This is not implying that `sosa:Platform` is not a subclass of `sosa:System`. The idea is that the systems collection will only include platforms that are also systems. Any other platform (e.g. a tree or a building) would just be a regular Feature as far as the API is concerned.

We will explain this better.

**Comment by KathiSchleidt** [comment]
Maybe define a dedicated class that is both a `sosa:Platform` as well as a `sosa:System`? To my memory, you're concern here was supporting drones where it seems you're integrating System functionality directly into the Platform. Why not define this special class?

**Comment by alexrobin** [comment]
Yes, the drone is one of those, but it really applies to all types of vehicles and other complex platforms, so we don't want to create classes for everything. We leave that up to the application domain.

In OWL, you could create an instance/individual that is both a sosa:System and a sosa:Platform without creating a more specialized class. That's what we are doing here with semantic tagging as well.
