### ISSUE TITLE
SamplingFeature collections correspond to `sosa:SampleCollection` (not `sosa:Sample`)

### ISSUE THREAD

**Issue by dr-shorthair** [opengeospatial/ogcapi-connected-systems#53]
in 14.6.  Feature Collections I see the note

> Sampling Feature collections are identified with the feature type sosa:Sample.

This is incorrect. Collections of Sampling Features correspond to `sosa:SampleCollection`

**Comment by alexrobin** [comment]
The feature type used here specifies the type of elements within the collection, not the collection itself.

**Comment by dr-shorthair** [comment]
OK. Maybe say "**Members of** Sampling Feature collections are identified with the feature type sosa:Sample."

**Comment by alexrobin** [comment]
Yes, I'll rephrase to make this clear.
This applies to all other feature type collections we defined in CS also.
