### ISSUE TITLE
Incorrect definitions for some path parameters in OpenAPI

### ISSUE THREAD

**Issue by avillar** [opengeospatial/ogcapi-connected-systems#57]
I am doing some tests with automatically downcompiling Connected Systems to an OpenAPI 3.0-compatible version (see [current draft](https://gist.github.com/avillar/b1596e634b4f330234028cc08957a344)).

I am getting some validation errors from path parameters:

- `/collections/{systemCollectionId}/items` (defined in [paths/systemsInCollection.yaml](https://github.com/opengeospatial/ogcapi-connected-systems/blob/947581c17c476805d7aec41d59a80cf55fd1309f/api/part1/openapi/paths/systemsInCollection.yaml)) includes `collectionId` (from [parameters/collectionId.yaml](https://github.com/opengeospatial/ogcapi-connected-systems/blob/947581c17c476805d7aec41d59a80cf55fd1309f/api/part1/openapi/parameters/collectionId.yaml)) instead. They should have the same parameter name.
- `/deployments/{deploymentId}/systems/{depSysId}` defines [a `deployedSystemId` parameter](https://github.com/opengeospatial/ogcapi-connected-systems/blob/947581c17c476805d7aec41d59a80cf55fd1309f/api/part1/openapi/parameters/deployedSystemId.yaml) instead of `depSysId` in its 3 operations [[1](https://github.com/opengeospatial/ogcapi-connected-systems/blob/947581c17c476805d7aec41d59a80cf55fd1309f/api/part1/openapi/paths/deployedSystemById.yaml#L7)][[2](https://github.com/opengeospatial/ogcapi-connected-systems/blob/947581c17c476805d7aec41d59a80cf55fd1309f/api/part1/openapi/paths/deployedSystemById.yaml#L31)][[3](https://github.com/opengeospatial/ogcapi-connected-systems/blob/947581c17c476805d7aec41d59a80cf55fd1309f/api/part1/openapi/paths/deployedSystemById.yaml#L56)]
- `/systems/{systemId}/samplingFeatures` does not define the `systemId` for its `post` operation [[4](https://github.com/opengeospatial/ogcapi-connected-systems/blob/947581c17c476805d7aec41d59a80cf55fd1309f/api/part1/openapi/paths/systemSamplingFeatures.yaml#L34)]
- `/deployments/{deploymentId}/systems` does not define the `deploymentId` paramter for its `post` operation [[5](https://github.com/opengeospatial/ogcapi-connected-systems/blob/947581c17c476805d7aec41d59a80cf55fd1309f/api/part1/openapi/paths/deployedSystems.yaml#L34)]

**Comment by alexrobin** [comment]
@avillar Thanks for your feedback. I'll make sure I think these issues ASAP.

**Comment by alexrobin** [comment]
FYI, Items 1 and 3 were fixed in 0e79f9b.
The other two are not relevant anymore as we removed the separate DeployedSystem resource in favor of subdeployments.
