### ISSUE TITLE
Inconsistent handling of DELETE via non-canonical URIs

### ISSUE THREAD

**Issue by SpeckiJ** [opengeospatial/ogcapi-connected-systems#66]
Currently it is inconsistent if deletion is only possible via the canonical URI, or via all URIs. Example:

`/req/create-replace-delete/sampling-feature` [link](https://docs.ogc.org/DRAFTS/23-001r0.html#_sampling_features):
```
The server SHALL support the REPLACE and DELETE operations at the Sampling Feature resources endpoints defined by the following URI templates:
    - {api_root}/samplingFeatures/{id}
    - {api_root}/systems/{sysId}/samplingFeatures/{id}
```

`/req/create-replace-delete/deployment` [link](https://docs.ogc.org/DRAFTS/23-001r0.html#_deployments)
```
The server SHALL support the REPLACE and DELETE operations at the Deployment resources endpoints defined by the following URI template:
    - {api_root}/deployments/{id}
```

Why is deletion via the non canonical URL "{api_root}/systems" possible for `samplingFeatures` but not for `Deployments`? They are both linked directly to systems and both have a canonical as well as a URI-via-systems.

**Comment by alexrobin** [comment]
Discussed during 09/19 telecon.
Remove the second endpoint `{api_root}/systems/{sysId}/samplingFeatures/{id}` for REPLACE, DELETE and UPDATE (Only allow these operations at the canonical endpoint).
