### ISSUE TITLE
Reference definition of Sensor Model from ISO 19130-3:2022

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-connected-systems#72]
The OGC Technical Committee requires that definitions from ISO/TC 211 standards be used, when they are available.

The definition of sensor model should be taken from ISO 19130.

This issue was originally discussed in the ogcapi-coverages repository.

https://github.com/opengeospatial/ogcapi-coverages/issues/177#issuecomment-1947964408

**Comment by alexrobin** [comment]
As discussed in the ogcapi-coverage issue, the definition of sensor model used in ISO19130 is way to restrictive as it only applies to imaging sensors. We cannot use it as-is for SensorML.

**Comment by alexrobin** [comment]
Discussed during 10/17 telecon.

The scope of ISO19130-3 is imagery sensor models, which makes the definition inappropriate for SensorML.
See discussion in https://github.com/opengeospatial/ogcapi-coverages/issues/177#issuecomment-1947964408
