### ISSUE TITLE
24-014: Example truncated in B.2.1. DataArray with inline values (curve)

### ISSUE THREAD

**Issue by hylkevds** [opengeospatial/ogcapi-connected-systems#80]
Example _B.2.1. DataArray with inline values (curve)_ shows a DataArray that specifies an `elementCount` of 5, but the data block only has 4 values. This is probably a result of a copy-paste error since the closing `]` of the `values`array is also missing.

**Comment by alexrobin** [comment]
Discussed during 10/31 telecon:
Ok, we will fix the example.
