### ISSUE TITLE
Add example of result@link with base64 encoded data URI

### ISSUE THREAD

**Issue by alexrobin** [opengeospatial/ogcapi-connected-systems#83]

**Comment by Sam-Bolling** [comment]
Example use case is a thumbnail image observation inserted to a database from a remote, in-situ unattended ground sensor.  The following GeoJSON file was transformed from an SOS 2.0 InsertObservation XML file.  It is intended to include a base64 encoded thumbnail JPEG image, but that information is currently missing.  There may be other errors, issues, items missing, or other best practices with the example below.  Considering the new CSAPI standards, what are the different approaches for encoding this data?  What are the best approaches for different goals (i.e., most readily processible by most clients; efficiency; etc.)?

{
"type": "Feature",
"geometry": {
   "type": "Point",
   "coordinates": [
     -77.3036270141602,
     34.6109237670898
   ]
},
"properties": {
   "resultTime": "2024-10-30T15:09:48Z",
   "resultTimestamp": 1730300988000,
   "featureType": "observation",
   "inboundEventQueueMessageId": "847d63b8-fa38-47e7-bb45-054c58ba075c",
   "observationId": "_12624d19-d2b7-43fe-8e4d-8fad4aefb0f8",
   "offering": "urn:ogc:object:Sensor: UGS:GROUP101-0001I",
   "observedProperty": "urn:gsw:def:phenomenon:radiance",
   "procedure": "urn:ogc:object:Sensor:UGS:GROUP101-0001I",
   "result": {
     "resultMessageType": "ACTIVITY",
     "resultDetail": "Image",
     "ampHoursRemaining": ""
   }
},
"id": "dd862fe3-1b11-4e68-943d-998653eedd2b",
"links": [
   {
     "href": "http://localhost:80/api/features/collections/observations/items/dd862fe3-1b11-4e68-943d-998653eedd2b",
     "rel": "self",
     "type": "application/geo+json",
     "hreflang": "en",
     "title": "This document",
     "length": null
   },
   {
     "href": "http://localhost:80/api/features/collections/observations",
     "rel": "collection",
     "type": "application/json",
     "hreflang": "en",
     "title": "This collection",
     "length": null
   }
]
}
